In [1]:
import numpy as np
import time

number = 100000
a = np.random.rand(number)
b = np.random.rand(number)

start_time = time.time()
dot_result = np.dot(a, b)
end_time= time.time()

print("dot product in vector result: {1}, cost time: {0:.6f} ms".format(1000*(end_time - start_time), dot_result))

start_time = time.time()
dot_result = 0.0
for i in range(number):
    dot_result += a[i] * b[i]
end_time= time.time()

print("dot product in loop result: {1}, cost time: {0:.6f} ms".format(10000*(end_time - start_time), dot_result))

dot product in vector result: 24975.28764609657, cost time: 138.844013 ms
dot product in loop result: 24975.28764609669, cost time: 441.429615 ms


In [2]:

test = np.array([0, 1, 2, 4])
exp_test = np.exp(test)
print("exp_test:")
print(exp_test)
print(exp_test.shape)
print(test.T)
print(np.dot(test, test.T))

test_4_1 = test.reshape(1,4)
print(test_4_1)
print(test_4_1.shape)
print(np.dot(test_4_1, test_4_1.T))

exp_test:
[ 1.          2.71828183  7.3890561  54.59815003]
(4,)
[0 1 2 4]
21
[[0 1 2 4]]
(1, 4)
[[21]]


In [3]:
a = np.random.randn(4,3)
print(a.shape)

b = np.random.randn(3,2)
print(b.shape)

#print(a*b) 
c = np.dot(a,b)
print(c.shape)
print(c)

(4, 3)
(3, 2)
(4, 2)
[[-0.0255694   0.83846922]
 [-0.59186966 -1.13080655]
 [ 0.10688641 -0.0926064 ]
 [-0.90679697 -1.64112028]]
